### PR TITLE
Improve tools tests

### PR DESCRIPTION
**Pull request by BuhtigithuB**

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
Please wait until this get resolve before merging this PR : https://groups.google.com/d/msg/web2py-developers/VFyn55pGi2E/Z8eJFz3qBwAJ

**Comment by BuhtigithuB** [comment]
Ready to merge now...

**Comment by leonelcamara** [comment]
Good job Richard!

**Comment by mdipierro** [comment]
Thanks Richard. Nice work!

**Pull request merged**
