### PR TITLE
More changes in List (request.args)

### PR DESCRIPTION
**Pull request by cassiobotaro**
- Better documented List
- Otherwise not binded with cast
- new tests to verify old behaviour 
- test otherwise without cast and defaut
- verify if behave like a list 
- more test with call function
Related to #955

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@nursix PR done, if you have another error, please report. Many thanksany thanks for all.

**Comment by cassiobotaro** [comment]
@mdipierro don't forget this commit before 2.10.5 to avoid problems.

**Comment by nursix** [comment]
Ah - ok, I see that this hasn't yet been committed to trunk (see my comment https://github.com/web2py/web2py/commit/c36c39178610867330ebf1927a2a3edeb7dcb35e#commitcomment-11104745).

Sorry for bothering you again, thanks for fixing it. Waiting for this to get merged then...

**Comment by mdipierro** [comment]
I will take this pull request but please reinstate DEFAULT = lambda: 0. it is kind of a convention everywhere in web2py.

**Pull request merged**
