### PR TITLE
Enhancement/d3 graph

### PR DESCRIPTION
**Pull request by willimoa**
Updated Welcome app to show model graphs with d3.
admin app's design.html view changed to check if d3_graph.js is in target app, otherwise uses existing graphviz code.

Graphviz code has not been altered and should still work for apps that haven't included the d3 code.
How does the welcome.w2p file get created ?  Should that be included in a Pull Request ?

### CODE REVIEW

**Comment by willimoa** [comment]
Hi, I hope I've done this correctly.  The last commit "Initial Pull Request..." has the changes for this enhancement.   The other commits appear to be my local commit after pulling from web2py/web2py.

**Comment by ilvalle** [comment]
A couple of things to do:
- you have to rebase your changes into 1 single commit, as a result all these 'merge branch' will go away
- you should not touch "gluon/packages/dal"
- appadmin.py and appadmin.html is copied also in applications/examples and applications/admin, consider to update these files too in order to keep everything in sync.

**Comment by Marlysson** [comment]
@willimoa , do you alter the dal package to do this feature? 

It's necessary?

**Comment by willimoa** [comment]
Thanks.  Extra commits are from my Pull from web2py.   No changes to dal.  Thanks for the tips, I'll clean up and rebase and try again.   
Do I need to include the welcome.w2p file ?

**Comment by ilvalle** [comment]
you have to remove 'extra commits', all those 'merge' commits are useless. Try to rebase your branch.
Regarding pydal, you have changed it, as a result, you have to revert that change. 
No, you should not include any welcome.w2p

**Comment by mdipierro** [comment]
@willimoa I like the idea of using d3.js. Can you do the change requested by ilvalle?

**Comment by willimoa** [comment]
Hi Massimo, I certainly can, just Messed up my git pull, pushes, and commits,   And my rebate didn't work.    Just getting up to speed with git.   I'll try again this week

**Comment by ilvalle** [comment]
@willimoa I suggest closing this PR and opening a new one. 
Looking at your web2py fork, an easier step is to start from scratch by removing and forking again web2py master branch. In the new PR, mind to commit only the files you have changed/added and try to work in a new branch (leave master untouched).

**Comment by willimoa** [comment]
Good Advice, thanks.

**Pull request closed without merging**
