### PR TITLE
Better test coverage for the validators module

### PR DESCRIPTION
**Pull request by leonelcamara**
I didn't test for these lines in date formatters:

        if year < 1900:
            year = 2000

Because I don't know what the hell they're doing there anyway.

### CODE REVIEW

**Comment by niphlod** [comment]
it's probably due to interpret 12-11-02 "forcing" it to be 02nd November 2002 instead of 02nd November 1902

**Comment by leonelcamara** [comment]
@niphlod then I will make sure to make a test for that in my next pull request to make sure the behavior isn't broken since people may depend on it.

**Comment by BuhtigithuB** [comment]
Hey guys... As validators.py module had be pointed out has one good piece
of web2py worth more testing, I undertake like Leonel to add more tests...

I start buy make the inventory which was difficult to have with Coverage
report... It was unclear which validator was tested and which not...

So I did that : https://github.com/web2py/web2py/pull/1212

I would like to start adding missing test... Though I feel this should be
merge before...

It ready to be merge.

Thanks to have a look.

Richard

**Comment by leonelcamara** [comment]
@mdipierro ping!

**Comment by mdipierro** [comment]
Fantastic! Thank you.

**Comment by mdipierro** [comment]
I had to merge this manually. because conflicting with BuhtigithuB. Apologies. All your changes should be there.

**Pull request closed without merging**
