### PR TITLE
New test suite for prettydate() + fix wrong number of days for month

### PR DESCRIPTION
**Pull request by BuhtigithuB**
More tests!!

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
I think this : 
```python
-    elif dt.days > 21:
+    elif dt.days >= 30:
```
was a bug...

??

**Comment by leonelcamara** [comment]
The days >21 was not really a bug more of a rounding up. I don't mind changing it but I wouldn't pick 30 because otherwise you will get stuff like 4 weeks which just looks bad because it would look better as 1 month.  So if you're going to change that change it to something between 21 and 27.

**Comment by BuhtigithuB** [comment]
@leonelcamara good point... and thinking to that with > 21 you got 3 weeks, I was concerned about that.. I will revert it...

**Comment by BuhtigithuB** [comment]
doh! you are rigth with 27...

**Comment by BuhtigithuB** [comment]
* [x] prettydate covered

**Comment by leonelcamara** [comment]
Ahahahah I like the comment, and it was needed so it doesn't cause confusion again in the future.

**Comment by BuhtigithuB** [comment]
haha!

**Comment by BuhtigithuB** [comment]
Tests pass previously here, the only change I made was fixing a typo in a comment "if -> is"... 

Can be merge.

**Pull request merged**
