### PR TITLE
enabled py35 unittests on win

### PR DESCRIPTION
**Pull request by ilvalle**
fixed minor issue with cacheOnDisk

### CODE REVIEW

**Comment by niphlod** [comment]
perfect. I wouldn't know about the utility to test 32 AND 64 archs in 2016 ... in any case paths to python should be either all with "\" or with "/".
Also, what about using https://github.com/Legrandin/pycryptodome instead of pycrypto ???

**Comment by ilvalle** [comment]
Which arch would you test?

**Comment by niphlod** [comment]
to avoid augmenting the matrix (and since I think Travis-CI has only 64 bit, too), I'd go for 64 bit only. @mdipierro, thoughts ? It may also be the time to package as a binary with pyinstaller rather than bbfreeze only 64 bit and/or think for the next release advertising py3 support a py3 binary.

**Comment by mdipierro** [comment]
@niphlod, I agree. @ilvalle, can I merge or should I wait for changes based on Simone's recommendations?

**Comment by ilvalle** [comment]
Updated as suggested, @mdipierro you can merge it.

**Pull request merged**
