### PR TITLE
make pymysql usable inside web2py

### PR DESCRIPTION
**Pull request by niphlod**

### CODE REVIEW

**Comment by ilvalle** [comment]
Since current contrib/pymysql supports py35, it should no longer necessary to force its installation in ```.travis.yml```. Would you update that file too?

**Comment by niphlod** [comment]
@ilvalle : done. I'll put a relevant note on the issue tracking the new release as we need to figure out and update all NEEDED dependencies before releasing (since it seems the new release will wait for "full" py3 support)

**Comment by ilvalle** [comment]
Web2py core passes almost all unittests using py3, however I wouldn't advertise the new release as py3 compatible because many features are not ready yet. The new release can advertise a _beta_ support or something like that.

Needed dependency are pycrypto (as an alternative to web2py aes) and pg8000. Updating the latter should not be a problem at all.

**Comment by ilvalle** [comment]
In travis build there are few warnings, as for example https://travis-ci.org/web2py/web2py/jobs/164235990#L377
few others are about pending deprecation at line 
```/home/travis/build/web2py/web2py/gluon/packages/dal/pydal/objects.py:2306: PendingDeprecationWarning: generator '__iter__' raised StopIteration```
Those warning regards mainly pydal, not sure are already tracked any where, @gi0baro ?

**Comment by niphlod** [comment]
@ilvalle: in any case, we SHOULD keep track of the "many features that are not ready yet", unless already tracked at #1353 . 
In addition, we exclusively run pydal tests (although the way we do it needs fixing) to test if the shipped drivers are working fine. I'm going to make a PR updating pg8000 and removing the dependency ASAP.
@mdipierro : this is good to merge anyway

**Pull request merged**
