### PR TITLE
Fix click popagation to both new and actual tab when CTRL+Click

### PR DESCRIPTION
**Pull request by BuhtigithuB**
This solved the issue #829

### CODE REVIEW

**Comment by niphlod** [comment]
imho it's "our own shallow trial to support multilevel menus", but @ilvalle can comment further.

**Comment by BuhtigithuB** [comment]
If find dropdown menu to be very usefull...

I think boostrap should implement it, and that will prevent us to fix it.

Progressive enhencement, Bootstrap no js = no dropdown menu, Bootstrap with
js = dropdown menu...

But I don't know why they don't do it...

Richard

**Comment by BuhtigithuB** [comment]
I may didn't understand completly the issue with boostrap menu dropdown :
https://groups.google.com/d/msg/web2py-developers/_7_1oVkq5K8/66wi3iSYfx4J

Richard

On Tue, Mar 3, 2015 at 11:08 AM, Richard Vézina <ml.richard.vezina@gmail.com
> wrote:

> If find dropdown menu to be very usefull...
>
> I think boostrap should implement it, and that will prevent us to fix it.
>
> Progressive enhencement, Bootstrap no js = no dropdown menu, Bootstrap
> with js = dropdown menu...
>
> But I don't know why they don't do it...
>
> Richard
>

**Comment by niphlod** [comment]
so this fix doesn't cut the deal and this PR is invalid, right ?

**Comment by BuhtigithuB** [comment]
No!

My PR is valid even if I don't fully understand all the aspect of
web2py_bootstrap.js which are as far as I understand is there to solve
issue with bootstrap not fully working dropdown menu for navbar in context
of web2py usage.

I fix a bug that is there since a long time which cause both new tab and
actual tab in which user CTRL+Click over navbar menu entries which
shouldn't be the case... Try the Welcome app by yourself you will see what
I am talking about...

I really hate that when I CTRL+Click over a hyperlink doing that for
nothing...

Richard

**Comment by niphlod** [comment]
let's wait for @ilvalle then. If I'm not mistaken he has the grip on the whole deal.

**Comment by ilvalle** [comment]
I used to click the mouse wheel to open links in new tabs. I tried this PR and it worked.

**Comment by BuhtigithuB** [comment]
Can this be closed?

**Comment by BuhtigithuB** [comment]
This one can be close : https://github.com/web2py/web2py/issues/829

Richard

**Pull request merged**
