### PR TITLE
cache (and compile) views, models and controllers

### PR DESCRIPTION
**Pull request by ilvalle**
Continuation of https://github.com/web2py/web2py/pull/1461 https://github.com/web2py/web2py/pull/1450
With this PR ```restricted()``` receives only compiled (and cached) code

### CODE REVIEW

**Comment by mdipierro** [comment]
I am going to revert this. If layout.html is edited, the change does not cause a recompilation of the extending pages.

**Comment by mdipierro** [comment]
Done. I only reverted changes to compileapp.

**Comment by niphlod** [comment]
ahem. https://github.com/web2py/web2py/issues/1310 is still fixed or not ?

**Comment by mdipierro** [comment]
No but in the push I just made yes but let's discuss on google group...

**Comment by niphlod** [comment]
as long as we don't reopen fixed bugs ^_^

2016-09-30 18:29 GMT+02:00 mdipierro <notifications@github.com>:

**Pull request merged**
