### PR TITLE
PEP8 fileutils py

### PR DESCRIPTION
**Pull request by BuhtigithuB**

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
Damn Github won't let me multiple PR even if it commit my change over another branch

**Comment by ilvalle** [comment]
@BuhtigithuB isn't a big deal.
You can surely create multiple PR, you normally have to create new branches starting from the master branch. From BuhtigithuB:pep8fileutils-py, do a ```git checkout master```, and then ```git checkout -b PR2```

**Comment by BuhtigithuB** [comment]
Can this one be merge? I have many more coming, they all have been made on their particular branch... Should I squash them?

**Comment by ilvalle** [comment]
It depends to the contribution you are proposing, usually is better to have
one commit for contribution (or file changed) but there isn't a general
rule about the 'size' of a commit/PR.

 Paolo

2015-03-07 13:51 GMT+01:00 BuhtigithuB <notifications@github.com>:

**Comment by BuhtigithuB** [comment]
Ok, I can make many PRs I don't care, it all PEP8 improvement to reduce pycham warning... The only thing is I really don't know why github don't let me make PR for a given branch only... Each time I try it keep adding all the differents changes I made over the different branch and the one on master... Even if I go to my branch and click make PR button beside the branch... Any idea?

**Comment by niphlod** [comment]
you're the only one having issues, so it's likely you are doing something wrong. I urge once again to review what you're sending in BEFORE hitting the "send PR" button.

BTW: if all of this is done to shut up pycharm's colorful warnings... I'd say shut pycharm warnings off until you master a taddle bit of git fu. Changing docstrings delimiters from ``"`` or `` ' `` to ``"""`` isn't improving web2py that much to justify you being angry at git.

**Comment by BuhtigithuB** [comment]
I like git!! :)

**Pull request merged**
