### PR TITLE
fix issue#1261: security issue: gluon.tools.Expose will follow symlinks

### PR DESCRIPTION
**Pull request by chenl**
By default don't allow to follow symbolic links outside of the exposed directory, unless `follow_symlink_out` is set to `True` in `Expose.__init__(...)`

This should resolve [security issue: gluon.tools.Expose will follow symlinks](https://github.com/web2py/web2py/issues/1261)

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
Can you squash your commits? I don't think it gonna get merged if you not do it... I don't know if you are familliar or not with git, but make sure you backup your cloned repository before trying anything if you want to make sure you are not loosing anything...

**Comment by mdipierro** [comment]
This does not pass tests. can you fix that? Thanks for you help very much otherwise.

**Comment by chenl** [comment]
@mdipierro: I am not sure what is wrong here:

$ python gluon/tests/test_tools.py -- pass
$ python web2py --run_system_tests -- error on a module I didn't touch
so I cloned a fresh copy of web2py/web2py and
$ python web2py --run_system_tests -- errors on a module I didn't touch

So I, no I figured that the error is due to a different commit.

Am I missing something?

**Comment by chenl** [comment]
@BuhtigithuB, regarding squashing. I didn't yet had my H-HA moment with Git - although I feet it is not far now - so I might take me some more effort squashing this pull request.

**Comment by BuhtigithuB** [comment]
Hello Chen,

Some times a commit may be responsible of a failing despite the fact the
final state pass, the intermediary commit may not pass the tests and the PR
fail...

Helps :
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by BuhtigithuB** [comment]
Any progress here?

**Comment by BuhtigithuB** [comment]
Hello Chen,

I give a look at you repo : https://github.com/chenl/web2py/commits/master

And it appears that you commit your changes against master... You supposed to create a branch for any change you undertake then push this branch on your repo (origin) then send PR...

**Comment by BuhtigithuB** [comment]
**git checkout master**  # just to make sure

Then:
**git checkout ad57c3c6136aa0b8c35a79606b94c097c7ab1c96**  # which is the previous commit before your oldest commit

Then:
**git checkout -b fix/expose-security-issue-1261**  # which create a new branch where your fix will be ending (what you should had done in the first place)

You should be on branch : fix/expose-security-issue-1261, you can check with : 
**git branch**  # the branch name should be highligthed

Then, I am less sure for the following command, what we need to do is to copy all the commits you made in the new branch that we created... But there is a lot of crap in it, as it a mix between your changes and others changes... So, I think to make it as simple as possible you should cherry pick all you commit into the new branch...

Here a reference : 
https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/

You can leave behind these commits as they didn't brings any value or cause issue : 
- chmod -x gluon/web2py.py 8cd08a917c44e93f7760291d1c6a738f15fbcf0e  # failed for some reason
- chmod -x fe493e0e4b53480fd9e089550ea33fd83fd6df96  # no value
- all the commit related to PEP8 enhancement or improving code presentation (you can do them later)
- also the ones about translation (do them later)
- let focus over the issue to be resolve

So let get back to the git command : 

git cherry-pick <sha-1>  # of the commits that address Expose issue expressly...

List of the good commits to me : 
a9d3e7d
0bdf99f
64de5cf
e43bc97
d0c4b1f
d1f6abb
4dd8745
60c8b47

So you have to repeat the git cherry-pick while being in your fix branch as many time as required... You may face some merge conflict but I think you will be ok. I am not sure if you need to commit after each cherry-pick or if it commited automatically you can check what git is doing with "git status" and gitg or git-cola (git front-end) that can help you visualize what you are doing... If you notice that change get apply to file but aren't be stage or commit you can "git commit -m 'copy original commit messare'" between cherry-pick...

Once done, you will need to push your change on your chenl/web2py repo : 
**git push origin fix/expose-security-issue-1261**
To upload you new branch ready for a clean PR

If you didn't have set a local git repo on your machine please follow : 
https://help.github.com/articles/cloning-a-repository/

Then configure remote (your github chenl/web2py) to push over :
https://help.github.com/articles/adding-a-remote/

Then configure upstream to fetch merge from web2py/web2py repo :
https://help.github.com/articles/configuring-a-remote-for-a-fork/
This will help you stay in synch with web2py, I let you read about git fetch upstream/git merge upstream master/git push origin master to keep you local and github own repo in sync

Once you have done that, you PR pass tests and get merge (thank me, just kidding), you have to get back to you master local branch and clean it up : 

To do so you have to : 
**git checkout master
git reset --hard ad57c3c6136aa0b8c35a79606b94c097c7ab1c96
git fetch upstream
git merge upstream/master
git push origin master**

You should be synched locally and on github

Only remaing tricky git intricacy that you need to keep in mind is to alwasy checkout master (which should be up to date - git fetch upstream/git merge upstream/master) before you create a new branch and checkout to it and start work on a new things as each time you create a branch it based on where you are so if you are in the branch (not master) and you create checkout a new branch it become _de facto_ the root of you branch...

Please do that ASAP as orther change are pending to be applies that we merge your work or we (you) will get into merge hell...

:)

**Comment by BuhtigithuB** [comment]
One last thing I should I state at the very top, copy your local repo into another location before aptempt any of the previous to not lost anything... So if you feel not sure about the result at any stage you can get back and start all over again fresh...

**Comment by BuhtigithuB** [comment]
Try that : 

git cherry-pick a9d3e7d449405a126b635b49d3e554448a0541a8
git cherry-pick 0bdf99f6e9f010668964926786dfbcef9cd1f7b3
git cherry-pick 64de5cfc895f939a1902efc0ed2dc37e45024822
git cherry-pick e43bc9771dc1d254d2db3aef73455da7f9975bb3  # merge hell start here
git cherry-pick d1f6abb199a0d4aadba0b495e5cdcd3db554eada
git cherry-pick d0c4b1fb1a14ea0b96c309c90d1686f7ec2f50ba
git cherry-pick 4dd8745eee4f717c167868fd5a1c51aec912fb46
git cherry-pick 60c8b4762e29c4a9827a5fd61a9c98850862e2da

**Comment by BuhtigithuB** [comment]
Maybe the easiest way could be that you start all over as you know what you did you can rapidly copy paste all you change over the web2py offical HEAD...

To do that : 
git checkout ad57c3c6136aa0b8c35a79606b94c097c7ab1c96

git fetch upstream  # after configure your repo
git merge upstream/master

I am not sure what will happen though, but I think you will ends with to HEAD you will defined the update to date one (the one you fetch and just merge as the main HEAD)... Then create a branch and copy paste your stuff then git add <files> then git commit/push and PR...

Sorry I have no more time now...

**Comment by chenl** [comment]
@BuhtigithuB, you already dedicated *lots* of time to help me with this.
I also used this time to brush up on my Git skills.

I guess I will need to cancel this commit request, fix my commit history on my localhost, and *force-push* it to https://github.com/chenl/web2py.
Then I will be able to re-submit a pull request for https://github.com/web2py/web2py.

I will re-read your advice to figure out if I can do this w/o a force-push.

Thanks for all your help.
Cheers,
Chen

**Comment by BuhtigithuB** [comment]
Hello Chen,

Happy to heard from you...

Start by this :

git checkout master
git checkout ad57c3c6136aa0b8c35a79606b94c097c7ab1c96
git checkout -b chenl-fetch-fix-expose-security-issue-stuff
git fetch https://github.com/chenl/web2py.git
git merge FETCH_HEAD chenl-fetch-fix-expose-security-issue-stuff

These commands will copy everything you did into an new
"chenl-fetch-fix-expose-security-issue-stuff

Then you can reset --hard ad57c3c6136aa0b8c35a79606b94c097c7ab1c96 as you
will have "backuped" your wrong commits ever master into a dedicated
branch...

Then you can checkout to master (or you will be already in master), let say
you have configuer upstream you fetch upstream, merge into master... You
got a up to date trunk...

Then you checkout -b fix/expose-security-issue

Then start fresh resolving the security issue by copy paste you code
back... Then commit. Try to make all you changes into a single commit and
commit all the related files that may have change for now let the comestic
changes that you made and focus on the security issue you identify...

If you need help setting up your local repo let me know...

Richard

**Comment by BuhtigithuB** [comment]
Any progress here?

**Comment by chenl** [comment]
Will re-send this PR squashed soon.

**Comment by chenl** [comment]
Submitted #1313 that should pass.

**Pull request closed without merging**
