### PR TITLE
added ssl option for tornado

### PR DESCRIPTION
**Pull request by dmvieira**

### CODE REVIEW

**Comment by titogarrido** [comment]
Will websocket_send work with wss?

Thanks,

Tito

On Thu, Oct 16, 2014 at 5:48 PM, mdipierro <notifications@github.com> wrote:

> Merged #511 <https://github.com/web2py/web2py/pull/511>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/web2py/web2py/pull/511#event-179681895>.
>



-- 

Linux User #387870
.........____
.... _/_õ|__|
..º[ .-.___.-._| . . . .
.__( o)__( o).:_______

**Comment by dmvieira** [comment]
Yes
Em 04/01/2015 21:44, "Tito Garrido Ogando" <notifications@github.com>
escreveu:

**Comment by titogarrido** [comment]
It worked when I used "https" in websocket_send:

*>>> websocket_send('https://127.0.0.1:8888 <https://127.0.0.1:8888>',
'Hello World', 'mykey', 'mygroup')''*

But for the WS javascript client I am getting a connection refused error:

*$.web2py.web2py_websocket('wss://127.0.0.1:8888/realtime/mygroup
<http://127.0.0.1:8888/realtime/mygroup>', function(e){
alert(e.data);*

*WebSocket connection to 'wss://127.0.0.1:8888/realtime/mygroup
<http://127.0.0.1:8888/realtime/mygroup>' failed: Error in connection
establishment: net::ERR_CONNECTION_REFUSED*

Did you get any issues? I am using a self generated cert file.

On Sun, Jan 4, 2015 at 10:01 PM, Diogo <notifications@github.com> wrote:

> Yes
> Em 04/01/2015 21:44, "Tito Garrido Ogando" <notifications@github.com>
> escreveu:
>
> > Will websocket_send work with wss?
> >
> > Thanks,
> >
> > Tito
> >
> > On Thu, Oct 16, 2014 at 5:48 PM, mdipierro <notifications@github.com>
> > wrote:
> >
> > > Merged #511 <https://github.com/web2py/web2py/pull/511>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/web2py/web2py/pull/511#event-179681895>.
> > >
> >
> >
> >
> > --
> >
> > Linux User #387870
> > .........____
> > .... _/_õ|__|
> > ..º[ .-.___.-._| . . . .
> > .__( o)__( o).:_______
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/web2py/web2py/pull/511#issuecomment-68655247>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/web2py/web2py/pull/511#issuecomment-68655876>.
>



-- 

Linux User #387870
.........____
.... _/_õ|__|
..º[ .-.___.-._| . . . .
.__( o)__( o).:_______

**Comment by dmvieira** [comment]
What version of web2py are you using? Please send me pm and I help you...
Em 04/01/2015 22:28, "Tito Garrido Ogando" <notifications@github.com>
escreveu:

> It worked when I used "https" in websocket_send:
>
> *>>> websocket_send('https://127.0.0.1:8888 <https://127.0.0.1:8888>',
> 'Hello World', 'mykey', 'mygroup')''*
>
> But for the WS javascript client I am getting a connection refused error:
>
> *$.web2py.web2py_websocket('wss://127.0.0.1:8888/realtime/mygroup
> <http://127.0.0.1:8888/realtime/mygroup>', function(e){
> alert(e.data);*
>
> *WebSocket connection to 'wss://127.0.0.1:8888/realtime/mygroup
> <http://127.0.0.1:8888/realtime/mygroup>' failed: Error in connection
> establishment: net::ERR_CONNECTION_REFUSED*
>
> Did you get any issues? I am using a self generated cert file.
>

**Comment by titogarrido** [comment]
Hi Diogo,

I am not able to see your email, it is set to notifications@github.com :)

I am using 2.9.11-stable+timestamp.2014.09.15.23.35.11
(Running on Rocket 1.2.6, Python 2.7.6)

On Sun, Jan 4, 2015 at 11:56 PM, Diogo <notifications@github.com> wrote:

> What version of web2py are you using? Please send me pm and I help you...
> Em 04/01/2015 22:28, "Tito Garrido Ogando" <notifications@github.com>
> escreveu:
>
> > It worked when I used "https" in websocket_send:
> >
> > *>>> websocket_send('https://127.0.0.1:8888 <https://127.0.0.1:8888>',
> > 'Hello World', 'mykey', 'mygroup')''*
> >
> > But for the WS javascript client I am getting a connection refused
> error:
> >
> > *$.web2py.web2py_websocket('wss://127.0.0.1:8888/realtime/mygroup
> > <http://127.0.0.1:8888/realtime/mygroup>', function(e){
> > alert(e.data);*
> >
> > *WebSocket connection to 'wss://127.0.0.1:8888/realtime/mygroup
> > <http://127.0.0.1:8888/realtime/mygroup>' failed: Error in connection
> > establishment: net::ERR_CONNECTION_REFUSED*
> >
> > Did you get any issues? I am using a self generated cert file.
> >
> > On Sun, Jan 4, 2015 at 10:01 PM, Diogo <notifications@github.com>
> wrote:
> >
> > > Yes
> > > Em 04/01/2015 21:44, "Tito Garrido Ogando" <notifications@github.com>
> > > escreveu:
> > >
> > > > Will websocket_send work with wss?
> > > >
> > > > Thanks,
> > > >
> > > > Tito
> > > >
> > > > On Thu, Oct 16, 2014 at 5:48 PM, mdipierro <notifications@github.com>
>
> > > > wrote:
> > > >
> > > > > Merged #511 <https://github.com/web2py/web2py/pull/511>.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/web2py/web2py/pull/511#event-179681895>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > Linux User #387870
> > > > .........____
> > > > .... _/_õ|__|
> > > > ..º[ .-.___.-._| . . . .
> > > > .__( o)__( o).:_______
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/web2py/web2py/pull/511#issuecomment-68655247>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/web2py/web2py/pull/511#issuecomment-68655876>.
> > >
> >
> >
> >
> > --
> >
> > Linux User #387870
> > .........____
> > .... _/_õ|__|
> > ..º[ .-.___.-._| . . . .
> > .__( o)__( o).:_______
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/web2py/web2py/pull/511#issuecomment-68656835>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/web2py/web2py/pull/511#issuecomment-68660207>.
>



-- 

Linux User #387870
.........____
.... _/_õ|__|
..º[ .-.___.-._| . . . .
.__( o)__( o).:_______

**Comment by dmvieira** [comment]
My twitter is diogomvieira
Em 05/01/2015 09:24, "Tito Garrido Ogando" <notifications@github.com>
escreveu:

> Hi Diogo,
>
> I am not able to see your email, it is set to notifications@github.com :)
>
> I am using 2.9.11-stable+timestamp.2014.09.15.23.35.11
> (Running on Rocket 1.2.6, Python 2.7.6)
>

**Pull request merged**
