### PR TITLE
security issue#1261: gluon.tools.Expose symlinks

### PR DESCRIPTION
**Pull request by chenl**
gluon.tools.Expose will follow symlinks outside of base directory.

By default don't allow to follow symbolic links outside of the exposed
directory, unless follow_symlink_out is set to True in
Expose.__init__(...)

### CODE REVIEW

**Comment by chenl** [comment]
I don't understand where the "codecov/changes — 17 files have unexpected coverage changes not found in diff." came from.

Should I worry about this?

**Comment by chenl** [comment]
Please not merge this yet.
There might be an issue here when base directory is '/'

**Comment by niphlod** [comment]
@chenl: any news on this ?

**Comment by chenl** [comment]
I have fixed the edge case in my repo. Closing this pull request and re-send it a-new.

**Pull request closed without merging**
