### PR TITLE
Auth refactor

### PR DESCRIPTION
**Pull request by leonelcamara**
Extracted many methods into a base class for more generic auth mechanisms.

Partially addresses #1526
Includes a solution for IS_LOWER and IS_UPPER validator problems I mentioned in #1353

### CODE REVIEW

**Comment by leonelcamara** [comment]
@mdipierro @niphlod @abastardi comments?

**Comment by niphlod** [comment]
sorry for the "not-so-active" review process but I'm swamped. A quick look (no tests, just general flow) gives me no shivers, so LGTM. We're not seeing a new stable for a while anyway, there's time to fix things.

**Comment by mdipierro** [comment]
I am revising this in the next few days.

**Comment by mdipierro** [comment]
This looks really good. I am going to take another couple of days to test it and then merge it.

**Comment by niphlod** [comment]
@leonelcamara : no sudo in travis, pleeeease !!!!!

**Comment by mdipierro** [comment]
I agree. But how do we solve the problem of the postgres installation? without that tests do not pass.

**Comment by niphlod** [comment]
solving an issue breaking how the suite runs isn't a fix, it's a band-aid ready to come off.

**Comment by niphlod** [comment]
see https://www.traviscistatus.com/incidents/ftk8v7ms1ks6 . they've been having problems with the container infrastructure.

**Comment by leonelcamara** [comment]
@niphlod sudo does make travis run slower because it can't use a container, but how does it break anything? All it does is make travis use the traditional build infrastructure we always used. 
  
This is just going around what is arguably a travis bug with their new docker containers as we aren't really using sudo anywhere I can see in our travis.yml, a bandaid indeed, hopefully we can remove it soon.

**Comment by niphlod** [comment]
Shouldn't change the output but I don't get the "pressure".
And btw "always" is relative, we use the container env since it has been
available (2 years maybe?)

Il 21 nov 2016 6:58 PM, "Leonel Câmara" <notifications@github.com> ha
scritto:

**Comment by leonelcamara** [comment]
@niphlod ok, you're obviously right on this one, I just changed it back, and things do seem to be fixed already.

**Comment by niphlod** [comment]
not obviously right, just faithful in travis which until now served us greatly. ^_^

**Comment by leonelcamara** [comment]
@mdipierro is there anything missing or that you need improved?

**Comment by nextghost** [comment]
I do have a feature request. I'd like an `Auth` method that will take a `dict` of user record values, register a new user and do all the background registration work, including sending a verification e-mail and requesting admin approval.

I need it for custom public registration form so using `register_bare()` would be a security disaster waiting to happen (if I screw up the check for existing records before calling it, it'll happily overwrite them; and it doesn't send verification e-mails anyway).

The new method should also have parameters for forcing/overriding e-mail verification and admin approval:
- `True` - do it regardless of global settings
- `False` - don't do it
- `None` (default) - use global settings

**Comment by mdipierro** [comment]
This looks great to me. If nobody objects I will merge this tomorrow.

**Comment by leonelcamara** [comment]
@nextghost that's actually one those things that really easy to do by subclassing AuthAPI

**Comment by nextghost** [comment]
@leonelcamara It's also one of those things that would be hard to maintain because it's duplication of existing upstream code that may change without notice.

**Comment by leonelcamara** [comment]
@nextghost I would be up for having a version, inheriting from this one that sent mails too in the trunk if it's a common usage. In fact I used to have emailing in AuthAPI, I decided to remove it because some people may want to inherit from AuthAPI and not have emails at all.  
  
Once in the trunk AuthAPI will not change, apart from bug fixing, without notice as web2py does try very hard to maintain backwards compatibility.

**Comment by nextghost** [comment]
@mdipierro If you're keeping this PR open only because of me, you can go ahead and merge it. I'll open a new pull request for my idea later.

**Comment by mdipierro** [comment]
I promise I will merge this very soon. this topic is very dear to me so I want to make sure I am 100% fine with it and I think I am.

**Pull request merged**
