### PR TITLE
add 'form-control' to _class of autocomplete input

### PR DESCRIPTION
**Pull request by remcoboerma**
This way it looks better because of bootstrap3 integration. 
http://getbootstrap.com/css/#forms

### CODE REVIEW

**Comment by mdipierro** [comment]
Thank you. I would like a second opinions about this PR. I understand the purpose but I really do not want to tie web2py more to bootstrap. If anything I want to untie it.

**Comment by mdipierro** [comment]
So no because you can do:

```
SQLFORM.widgets.autocomplete._class = "string form-control"
```

and add any class you want.

**Comment by remcoboerma** [comment]
Thanks for that. But does untying break backward compatibility? It all depends on what one would consider backward compatible i guess. Don't get me wrong, it would be great to get web2py frontend agnostic but still easy enough to work with all different kinds of these frameworks.

**Comment by mdipierro** [comment]
Working (slowly) for some time for a new library to replace SQLFORM. We are not removing SQLFORM but it has unfixable problems. The new one will be similar but not backeard compatible and have an easier way to couple css to the form.

**Pull request closed without merging**
