### PR TITLE
added HttpOnly cookies (default)

### PR DESCRIPTION
**Pull request by ShySec**
added unit tests for cookie layout, secure cookies, and HttpOnly cookies
Session.httponly_cookies=False to revert HttpOnly cookies

### CODE REVIEW

**Comment by ShySec** [comment]
https://www.owasp.org/index.php/HTTPOnly#What_is_HttpOnly.3F

**Comment by ShySec** [comment]
previous PR https://github.com/web2py/web2py/pull/1046

**Comment by mdipierro** [comment]
Let's wait for niphlod's comment than I will review it. ;-)

**Comment by ShySec** [comment]
Ping. I believe this update meets all niphlod's previous concerns (namely applying post-2.12.3-release and the addition of regression tests).

**Comment by niphlod** [comment]
pong, @niphlod was on holidays, but planning for a big return on the scenes. 
Joking (on the *big* return), but hey, it's been 5 days, not a month...

BTW: tests for the new feature are there, but that piece of code gets called for every kind of session, file, db or cookie based. Frankly, on 4 or 5 times I got my hands dirty on globals.py it resulted in a mess. 
It was since rewritten basically from the ground up to eliminate the complications, but the result was not really __that__ linear. That's why I tread lightly  in regards of this module.

BTW2: @mdipierro with all our "OWASP-fixer-friends", why didn't this come up earlier ? :D

BTW3: I assume everyone tested components and ajax with this already. From the specs, adding httponly in a modern browser affects only "reading document.cookie", that returns an empty string...but $.ajax() should be allowed to copy the cookie and send it back to the server ... but one can't ever **be sure** of "specs" without testing.

**Comment by ShySec** [comment]
I did test components and AJAX. For clarity sake, jQuery ($) cannot access or copy the cookie, but $.ajax will include the HttpOnly cookie (provided by the browser).

**Comment by mdipierro** [comment]
I reviewed this code and it looks good to me. The rewrite does not change behavior. The change in functionality is optional and comes with tests. It addresses a potential vulnerability. Good job.

**Pull request merged**
