### PR TITLE
added default HttpOnly cookies

### PR DESCRIPTION
**Pull request by ShySec**
https://www.owasp.org/index.php/HTTPOnly#What_is_HttpOnly.3F

supports "session._js_cookies = True" to restore old behavior

### CODE REVIEW

**Comment by niphlod** [comment]
uhm. "_js_cookies" doesn't really sound as what it provides. Maybe httponly_cookies is best. And I'd go for issuing httponly cookies by default without the option to remove the httponly part

**Comment by ShySec** [comment]
I agree with default-secure options that protect users. At the same time, I agree with supporting non-standard configurations without modifying web2py source code. The new configuration variable (session.httponly_cookies) would need to be deliberately set in all sessions, which should make the setting better scoped and more obvious than web2py source code modification (and only slightly harder).

**Comment by niphlod** [comment]
this wasnt't ready to merge!

**Comment by mdipierro** [comment]
I thought he made the changes you requested.

**Comment by niphlod** [comment]
uhm. a part from the fact that we rarely touch globals without 31290 cross-checks, have someone tested it ?

**Comment by mdipierro** [comment]
reverted

**Comment by ShySec** [comment]
I don't know what 31290 references. How do we move this forward?

**Comment by niphlod** [comment]
adding tests, mainly. 
The "anti-rush" was because a new version was going to be released (2.12.3) which was supposed to be just a fix for an incorrect pydal inclusion. 
We can move with the usual schedule here, but regression tests IMHO should be added to avoid regression(s) in a piece of code that gets executed at EVERY request.

**Comment by ShySec** [comment]
It doesn't appear I can advance this PR directly; submitting a new one with all updates + tests.

**Pull request merged**
