### PR TITLE
nginx/uwsgi installation script: consistent services start for systemd with systemctl command

### PR DESCRIPTION
**Pull request by zvolsky**
_I'm sorry for changes/commits from experimental branch, but I have removed form.py later; so all changes in the pull request are in the nginx/uwsgi script file only_

I have this script just tested on clean (new) cloud Debian Jessie machine.
Works well.

Before the testing I made on the machine this and only this (as root of course):

apt update
apt dist-upgrade
apt install sudo
apt install git
git clone https://github.com/web2py/web2py.git
cd web2py/scripts
chmod +x setup-web2py-nginx-uwsgi-ubuntu.sh
./setup-web2py-nginx-uwsgi-ubuntu.sh

After that both services are running and on http://xxx.xxx.xxx.xxx lives the welcome application.

Best regards, Mirek
PS: I use forpsi hosting, virtual machine 20G SSD for 1.50$ / month, and seems it is for web2py excellent.

### CODE REVIEW

**Comment by mdipierro** [comment]
I am using Linux version 4.2.0-36-generic (buildd@lgw01-38) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #41~14.04.1-Ubuntu SMP Tue Apr 19 17:03:32 UTC 2016 and systemctl commands do not work there while  /etc/init.d/... start/stop work fine. The latter seems to be more general. Can you make the case for systemctl and how to get it to work on Ubuntu 14.04?

**Comment by niphlod** [comment]
Didn't we agree on stopping refactoring this?
Il 20 mag 2016 02:01, "mdipierro" <notifications@github.com> ha scritto:

**Comment by zvolsky** [comment]
I'm very sorry for it.
My idea was that "systemctl" works everywhere and it is the preffered way how to to id.
Mistake...
So please reject this pull request.

**Comment by mdipierro** [comment]
No problem. Thank you for your help.

**Pull request closed without merging**
