### PR TITLE
Issue/1451

### PR DESCRIPTION
**Pull request by kelsa-pi**
PR for issue 1451 - new sr-lt and sr-cr translation.

PS: My first PR ever

### CODE REVIEW

**Comment by ilvalle** [comment]
Mind that many changes you proposed are already in master branch.

**Comment by kelsa-pi** [comment]
My PR is about sr-lt.py and sr-cr.py files only.

**Comment by ilvalle** [comment]
No, see the tab "File changed" https://github.com/web2py/web2py/pull/1475/files

**Comment by niphlod** [comment]
closing since https://github.com/web2py/web2py/pull/1476 landed

**Pull request closed without merging**
