### PR TITLE
Test Mail.Attachment by mailing test_tools.py itself

### PR DESCRIPTION
**Pull request by leonelcamara**

### CODE REVIEW

**Comment by BuhtigithuB** [comment]
watchout merge hell!!

**Comment by leonelcamara** [comment]
@BuhtigithuB it should be ok since I only touched the Mail test in test_tools.py and you only changed Auth, it should be able to merge automatically.

@niphlod I got the scheduler test to count subprocesses in coverage by running the scheduler using coverage itself, make sure to review that commit

**Comment by niphlod** [comment]
@leonelcamara : uhm ... sure that it works for you? Before pushing my PR I tried pretty much every variation already and got some times similar errors as current tests.....both travis-ci and appveyor are saying it's not working, and my computer too ... does it really work on yours ?

**Comment by leonelcamara** [comment]
@niphlod It works for me, it doesn't work on travis-ci, I think it's because it's using coverage 4.0.3 while I'm using 4.1b2 is it possible to tell travis-ci to use a newer version of coverage?

**Comment by niphlod** [comment]
doesn't even on appveyor though......... let me try on my computer.

**Comment by leonelcamara** [comment]
appveyor is also using 4.0.3

**Comment by niphlod** [comment]
well, instead of make tests fail, given that 4.1b2 is a beta, I'd stay with 4.0.3 until it gets released... even if that means not having code coverage for 40 lines of scheduler.py

**Comment by leonelcamara** [comment]
Agreed, I'll remove that commit I guess I'll try again when coverage 4.1 is properly released.

**Pull request closed without merging**
