### PR TITLE
From DAL to pyDAL as git submodule

### PR DESCRIPTION
**Pull request by gi0baro**
Implementation strategy:
* git submodule in `gluon/packages/dal`
* pyDAL module import to sys.modules in `gluon/__init__.py`

Major changes in web2py:
* dal imports rewrite
* DAL subclassing to add web2py's features
* pyDAL exceptions handling
* removed old DAL tests
* `RuntimeError` exception when pydal is not available
* introduced specific web2py DAL tests (to be expanded)

TODO:
* check applications for old imports
* check contrib modules for old imports

### CODE REVIEW

**Comment by ilvalle** [comment]
To better track the integration of pydal I'd rebase the PR

**Comment by gi0baro** [comment]
@ilvalle why that?
I think it's more convenient using some steps.

**Comment by gi0baro** [comment]
I've added 2 more commits, to track latest pyDAL and not turn back to older dal code on web2py, and one to add web2py's contrib drivers onto pyDAL.
@ilvalle the drivers integration doesn't include `pg8000` as it needs to be updated in web2py to work on latest pyDAL.

**Comment by gi0baro** [comment]
I expect these steps:
* Merge of this PR
* Update of `pg8000` in contrib and uncomment of related lines in `gluon/dal.py`
* Tests for contrib drivers

@mdipierro @ilvalle can we do these steps?

**Pull request merged**
