### PR TITLE
PEP8 enhancements, improve docstring and some vars rename

### PR DESCRIPTION
**Pull request by BuhtigithuB**

### CODE REVIEW

**Comment by niphlod** [comment]
maybe next time pull from master AND then spend time on it.......

**Comment by niphlod** [comment]
directly from https://github.com/BuhtigithuB/web2py, 2016-01-14 16.35.52 UTC ..... 

      This branch is 108 commits behind web2py:master.

**Comment by BuhtigithuB** [comment]
I pull it yesterday... Sorry would you like me to resend a PR with update
master, it not a big deal to do it...

Richard

**Comment by BuhtigithuB** [comment]
Wait, it because I forgot to update my depot...

**Comment by BuhtigithuB** [comment]
May I delete this PR and recreate it or it too late?

**Comment by niphlod** [comment]
there's no point. the whole file changed. open another PR .

**Comment by BuhtigithuB** [comment]
Done!

Richard

**Pull request closed without merging**
