### PR TITLE
Added CAPTION to gluon/html.py as it is often used with tables. 

### PR DESCRIPTION
**Pull request by gorosz**
Also included test for new tag in gluon/tests/test_html.py

### CODE REVIEW

**Comment by niphlod** [comment]
we have a strict policy to avoid cluttering the global namespace.......... use TAG.caption() instead...

**Comment by gorosz** [comment]
The problem whit that is it wrap the caption into a new tbody tag which can be problematic with some javascript/jquery applications for example dataTables

**Comment by niphlod** [comment]
what do you solve with CAPTION that you can't with TAG.caption()?

**Comment by gorosz** [comment]
If I define the CAPTION class I can add it to the TABLE's _fixup method so it is not wrapped in a TR and the html rendering engine does not create a new tbody for that TR element.
If it is possible with TAG.caption() it is absolutely fine.

**Comment by leonelcamara** [comment]
Gorosz has a point. Maybe add a test to make sure a caption in a table doesn't get wrapped.
  
We should probably just remove automatic wrapping (backwards incompatible sadly) otherwise this is the only way I see to solve it.

**Comment by mdipierro** [comment]
The new helpers in Form.py do not do automatic wrapping. So web3py will not do it.

**Comment by mdipierro** [comment]
One solution here is to change the behavor of TABLE fixup. I will do so.

**Comment by mdipierro** [comment]
I do not want to bloat this. So no for now.

**Pull request closed without merging**
