### PR TITLE
Jwt renew fix

### PR DESCRIPTION
**Pull request by michele-comitini**

### CODE REVIEW

**Comment by niphlod** [comment]
does this superseed https://github.com/web2py/web2py/pull/1338 ?

**Comment by michele-comitini** [comment]
@niphlod Yes it is a merge with that so I closed #1338
btw I made more tests yet codecov keeps complaining??

2016-06-01 0:09 GMT+02:00 niphlod <notifications@github.com>:

**Comment by niphlod** [comment]
I'll ask codecov devs because technically https://github.com/web2py/web2py/blob/master/.codecov.yml#L9 and following have been added explicitely to avoid making the report complaining about coverage changed in "unexpected" paths.

**Comment by niphlod** [comment]
hopefully once #1345 is in it should stop

**Pull request merged**
