### PR TITLE
Issue/1472

### PR DESCRIPTION
**Pull request by willimoa**
Replaced by d3 force graph.
graphviz related code removed in this PR

### CODE REVIEW

**Comment by willimoa** [comment]
What to do about the codecov fail ?

**Comment by willimoa** [comment]
Hi codecov is failing due to gluon/languages.py and gluon/rocket.py which is not part of the PR.  Can this be approved please?

**Comment by ilvalle** [comment]
Don't worry about codecov, @mdipierro will merge it
Regarding 'js/d3.min.js' and 'd3.min.js', they should be placed in admin/static. All `response.files.append(URL('static','js/d3.min.js'))` should point there.

**Comment by mdipierro** [comment]
+1

**Comment by willimoa** [comment]
Done, and the css file also.

**Comment by ilvalle** [comment]
Mind that any files regarding d3 should be removed from example/static and welcome/static. Update any `response.files.append(URL('static','js/d3.min.js'))` to point admin/static

**Comment by willimoa** [comment]
Makes sense.   Changes made.

**Comment by mdipierro** [comment]
Is this ready to be merged?

**Comment by willimoa** [comment]
Yes, ready to go !

**Pull request merged**
