### PR TITLE
Make ldap_auth a bit more DRY

### PR DESCRIPTION
**Pull request by BuhtigithuB**
Hello,

I make this part a little more DRY for further change that coming.

Thanks...

### CODE REVIEW

**Comment by niphlod** [comment]
IMHO this should be handled by the dal layer.

**Comment by BuhtigithuB** [comment]
I know, ldap_auth shouldn't update db, it makes no sens because it if
fields name change ldap_auth break... Though thing are how they are... To
me, ldap_auth should be rewrite... Each time I try to change something in
it, I get crazy...

:)

Richard

**Comment by BuhtigithuB** [comment]
There is also a big issue with the way it handle username authentification
that cause in some circumstance the duplication of user record... This also
in part related to the fact that ldap_auth update directly the db without
passing by web2py... And to fix this, I had to change web2py and ldap_auth
because the later handle badly the username credentials...

**Comment by mdipierro** [comment]
Yes, this should be handled by the DAL layer but, until then, this is an improvement.

**Comment by BuhtigithuB** [comment]
:)

**Pull request merged**
