### PR TITLE
added newer Recaptcha2 class to deal with v2.0. Fixes #919

### LINKED ISSUE #919: Support the new reCaptchas
Are there any plans to support the new "I'm not a robot" reCaptchas out of the box? I know the old styled recaptchas are currently supported, but it would be better to use the newest.

https://developers.google.com/recaptcha/

### PR DESCRIPTION
**Pull request by niphlod**
Improvements over the "old" v1.0
- behaves well also without javascript
- use_ssl is redundant, v2.0 works only in https mode
- ajax is not useful anymore as the newer API is a lot easier

Adjusted also the addrow() method that was missing newer formstyles.

### CODE REVIEW

**Comment by mdipierro** [comment]
Do we have to call this Recaptcha2? can we replace the old one?

**Comment by niphlod** [comment]
widgets dimensions aren't the same: it'll break existing designs, although it won't break functionality. Moreover, arguments for the old one don't match the newer. We can recommend this over the old, but not replace it.

**Comment by mdipierro** [comment]
Can we expose a single interface that renders as one or the other depending on the arguments?

**Comment by niphlod** [comment]
Don't think so, sorry but they're too different.

**Comment by mdipierro** [comment]
OK. But eventually we should break tools into sub modules.

**Comment by niphlod** [comment]
you're preaching to a quire. Extrapolating recaptcha and recaptcha2 is by far the easiest sub-task in the great project of breaking tools.py.

**Comment by mdipierro** [comment]
I think each class in tools is its own universe. They do not depend on each other.

**Pull request merged**
