### PR TITLE
Add FlexibleService, which allows @service-style methods with varargs

### PR DESCRIPTION
**Pull request by BrenBarn**
This addresses #1561 .

I don't know what your testing procedure is for things like this.  I see that the current test_tools.py just has TestService as "todo" so this would be in line with that.  I've done some simple tests by creating a sample app and calling the service endpoints and it works.  In any case, this change only adds a new class, so it shouldn't affect any existing behavior.

The PR defines a new FlexibleService class that inherits from the existing Service.  It overrides that various `serve_whatever` methods so that instead of using `universal_caller`, they use a method `call_service_function` provided by FlexibleService.  The default implementation of this method just directly calls the function, passing whatever arguments were given to the "call" controller function.  This means the service function can accept `*args` and/or `**kwargs`.  This also means that if the service function doesn't accept the passed arguments, an exception will be raised, rather than returning an "Object does not exist" 404 as Service currently does.  Using a method for `call_service_function` instead of a module-level function means that it's possible to write new classes that inherit from FlexibleService and add more sophisticated argument checking if they want to.

The new FlexibleService class also addresses bug #1560 by fixing the errors in the CSV and XML methods so that they store and find the procedures in the right place.  This does not, however, fix the bug in Service itself that stores these procedures in the wrong place.

### CODE REVIEW

**Comment by abastardi** [comment]
I don't think we should simply add a whole new class to the API (particularly given that it simply duplicates most of the original code, which is not DRY). Rather, we should fix the current `Service` class by changing `universal_caller` to accept arbitrary arguments (though moving it to a method of the `Service` class is probably a good idea, to facilitate subclassing). If there is some good reason to retain the current behavior as the default, then we should simply add an argument to the `Service.__init__` method to enable the new behavior as an option -- something like:

    class Service(object):

        def __init__(self, environment=None, allow_packing=False):
            ...
            self.allow_packing = allow_packing

        def universal_caller(self, f, *args, **kwargs):
            if self.allow_packing:
                [new code]
            else:
                [old code]

And then change later calls from `universal_caller(...)` to `self.universal_caller(...)`.

**Comment by mdipierro** [comment]
I agree with Anthony. Let me know if anybody is willing to work on it, else I will do this.

**Comment by BrenBarn** [comment]
Note that that can potentially change the behavior of existing uses of `Service`, although the kinds of usages that it would break are probably uncommon.  I agree it would be preferable but I hesitated to do that because of how it might change existing behavior.

**Comment by mdipierro** [comment]
I do not think it would be a problem, because, as Anthony suggests there would be an optional argument to the Service() constructor (allow_arg_packing) and if false the current behavior stays. If True it will follow the new behavior you propose. Looks like you already have some code to test this on so would be great if you could do it.

**Comment by BrenBarn** [comment]
Do we consider `universal_caller` as a public function from `gluon.tools` that people might be using on its own?  Or is it okay to move it inside `Service` as a method?

**Comment by abastardi** [comment]
I don't think `universal_caller` is considered part of the public API, so should be safe to move it inside the `Service` class (if there is any concern, we could always leave it where it is but still create a new method in the class for actual use by the class).

The only question is whether `allow_arg_packing` should default to `False` (identical to the current behavior) or `True` (more convenient, though if this breaks backward compatibility for anyone, they would have to explicitly set the arg to get the old behavior). I lean toward `True` because it's not clear this would really be a compatibility issue, and if so, probably very rarely, and with an easy fix.

@mdipierro, thoughts?

**Comment by BrenBarn** [comment]
I changed the code so it modifies Service instead of adding FlexibleService.  I left `universal_caller` in place, but just added the `call_service_function` method that calls `universal_caller` if we want the old behavior, or doesn't call it if we want the new behavior.

Service now has an argument to decide between old and new behavior.  I named this argument `check_args`, which I think more accurately reflects its meaning: the new behavior is not just "allow passing args/kwargs"; it's "just pass everything, without checking what arguments the service function accepts at all".  The default is False, i.e., don't check args, which means this defaults to the new behavior, in line with what you suggested.

**Comment by BrenBarn** [comment]
Not sure what is up with the failing tests, they don't seem to involve Service at all. . .

**Comment by niphlod** [comment]
@BrenBarn not your fault. @mdipierro checked in some code that shouldn't have been committed in master.

**Comment by BrenBarn** [comment]
Okay, well, let me know if/when I should rebase and update the PR.

**Comment by mdipierro** [comment]
Hello @BrenBarn, I merged it and apologies it took me so long. But can you please write a line in the book to describe the new syntax?

**Comment by BrenBarn** [comment]
Sorry, I've been away from this for a bit.  I'm not sure what really needs to be added to the docs.  It's rather that the existing documentation didn't document the limitations of the previous implementation.  It was never documented that extra arguments would be silently ignored, or that the service function couldn't accept args/kwargs.  We could add a note saying explicitly that you now can do that?

**Pull request merged**
