### PR TITLE
Changed URL validation to use urlparse instead of regex for spliting …

### LINKED ISSUE #1598: URL having character | in fragment part, does not pass IS_URL validator
`IS_URL()` validator doesn't accepts following url and similar google group urls. 
Example: https://groups.google.com/forum/#!searchin/web2py/url$20validation$20problem|sort:relevance/web2py/69KmsrYAF44/Sgk_hA_6TlcJ

Character | should be allowed in fragment part of the url

### PR DESCRIPTION
**Pull request by leonelcamara**
…the URL

Enabled test_is_url in Python 3 since it is now passing
This might be one of the last fixes to #1353
Fixes #1598

### CODE REVIEW

**Comment by leonelcamara** [comment]
Everyone please review this as much as possible, I only wanted to fix #1598 but sneaky @ilvalle suggested I could use urlparse in my previous pull request #1643. The changes ended up being much more extensive and harder than I thought. Ohh well, at least this is one of the most tested files in web2py.

**Comment by ilvalle** [comment]
The PR looks go to me.
A minor question, why is the try/except no longer necessary in https://github.com/web2py/web2py/pull/1644/files#diff-1e4f774e944ce88607f6bc3debe6f0b7L1473 ?

Regarding https://github.com/web2py/web2py/issues/1353 few checkboxes have been fixed, @niphlod would you update it?

**Comment by niphlod** [comment]
Going to. You know the list of ones I forgot excluding this, of course?

Il 07 giu 2017 18:08, "ilvalle" <notifications@github.com> ha scritto:

**Comment by leonelcamara** [comment]
@ilvalle That try except was actually quite a weird situation because test_is_url.py in https://github.com/web2py/web2py/pull/1644/files#diff-99e8ab468a65ee093a207f013a521837R592

In a line that I have not changed, actually tests that an exception is raised and try except was preventing the exception from being raised in python 3 causing the test to fail.  In python 2 it actually seemed to work before because it would raise an UnicodeError inside the except clause whereas that did not happen with python 3.

**Comment by ilvalle** [comment]
@leonelcamara thank for the explanation
@niphlod in #1353 you can check, `IS_LENGTH`, `IS_IP`, `port web2pyDialog`, `execute the entire test suite on 3.5`. Regaring `cache.disk` I'd ear @leonelcamara option

**Comment by leonelcamara** [comment]
cache disk tests seem to pass pretty well on python 3 so it seems to be fine now.

**Comment by niphlod** [comment]
#1353 updated.

**Comment by ilvalle** [comment]
@niphlod you can check `execute the entire test suite on 3.5`, `test_old_doctests` is the only one missing and it isn't worth to port it.

**Comment by niphlod** [comment]
@ilvalle : are you saying that utf8.py and markmin don't need to be tested ? doctests cover html.py, utf8.py and markmin2hhtml. html.py has a corresponding unittest suite, the other 2 no. 

BTW: here is kinda offtopic, better discussing #1353 directly

**Comment by mdipierro** [comment]
Can you please resolve the conflicts with master and resubmit?

**Comment by leonelcamara** [comment]
@mdipierro done, ironically the conflict arose because of my other pull request being merged which changed the same import line.

**Pull request merged**
